# Generated by Django 2.2.3 on 2019-07-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_song_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='user',
        ),
    ]
