# Generated by Django 2.2.3 on 2019-07-09 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0005_remove_song_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ManyToManyField(default=1, to=settings.AUTH_USER_MODEL),
        ),
    ]
